# permissions for end users to view sqbapplications.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sqbapplication-viewer-role
rules:
- apiGroups:
  - qa.shouqianba.com
  resources:
  - sqbapplications
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - qa.shouqianba.com
  resources:
  - sqbapplications/status
  verbs:
  - get
