# permissions for end users to view sqbdeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sqbdeployment-viewer-role
rules:
- apiGroups:
  - qa.shouqianba.com
  resources:
  - sqbdeployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - qa.shouqianba.com
  resources:
  - sqbdeployments/status
  verbs:
  - get
