# permissions for end users to edit sqbdeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sqbdeployment-editor-role
rules:
- apiGroups:
  - qa.shouqianba.com
  resources:
  - sqbdeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - qa.shouqianba.com
  resources:
  - sqbdeployments/status
  verbs:
  - get
