apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: elasticenvmirrors.qa.shouqianba.com
spec:
  group: qa.shouqianba.com
  names:
    kind: ElasticEnvMirror
    listKind: ElasticEnvMirrorList
    plural: elasticenvmirrors
    singular: elasticenvmirror
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: ElasticEnvMirror is the Schema for the elasticenvmirrors API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: ElasticEnvMirrorSpec defines the desired state of ElasticEnvMirror
          properties:
            args:
              items:
                type: string
              type: array
            command:
              type: string
            env:
              items:
                properties:
                  name:
                    type: string
                  value:
                    type: string
                required:
                - name
                type: object
              type: array
            healthCheck:
              properties:
                path:
                  type: string
                port:
                  type: integer
              required:
              - path
              - port
              type: object
            hostAlias:
              items:
                properties:
                  hostname:
                    type: string
                  ip:
                    type: string
                required:
                - hostname
                - ip
                type: object
              type: array
            image:
              description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                Important: Run "operator-sdk generate k8s" to regenerate code after
                modifying this file Add custom validation using kubebuilder tags:
                https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              type: string
            path:
              items:
                properties:
                  host:
                    type: string
                  path:
                    type: string
                required:
                - host
                - path
                type: object
              type: array
            ports:
              items:
                properties:
                  containerPort:
                    type: integer
                  port:
                    type: integer
                  protocol:
                    type: string
                required:
                - containerPort
                - port
                type: object
              type: array
            resources:
              properties:
                limits:
                  description: ElasticEnvProjectResource 资源限制
                  properties:
                    cpu:
                      type: string
                    memory:
                      type: string
                  type: object
                requests:
                  description: ElasticEnvProjectResource 资源限制
                  properties:
                    cpu:
                      type: string
                    memory:
                      type: string
                  type: object
              type: object
            selector:
              description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                Important: Run "operator-sdk generate k8s" to regenerate code after
                modifying this file Add custom validation using kubebuilder tags:
                https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              properties:
                plane:
                  type: string
                project:
                  type: string
              required:
              - plane
              - project
              type: object
            volumes:
              items:
                properties:
                  source:
                    type: string
                  target:
                    type: string
                  type:
                    type: string
                required:
                - source
                - target
                type: object
              type: array
          required:
          - selector
          type: object
        status:
          description: ElasticEnvMirrorStatus defines the observed state of ElasticEnvMirror
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
