name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
    - master

jobs:
  build:
    name: Test and Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ^1.17
    - name: Generate code and manifests
      env:
        GO111MODULE: on
        TAG: ${{ env.GITHUB_REF_SLUG }}
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin # temporary fix. See https://github.com/actions/setup-go/issues/14
        make generate
        make manifests
    - name: Test
      run: |
        go test -race -covermode=atomic -v -coverpkg github.com/wosai/elastic-env-operator/domain/handler ./...
    - name: Test Coverage Report
      run: bash <(curl -s https://codecov.io/bash)
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      timeout-minutes: 20
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: |
          ghcr.io/shouqianba-ft/elastic-env-operator:latest
        platforms: linux/amd64
        labels: ${{ steps.meta.outputs.labels }}
