name: master

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Test
      run: go test -race -coverprofile=coverage.txt -covermode=atomic -v ./...

    - name: Test Coverage Report
      run: bash <(curl -s https://codecov.io/bash)

  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    env:
      RELEASE_VERSION: v0.17.0
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Install Operator SDK
        run:  |
          curl -LO https://github.com/operator-framework/operator-sdk/releases/download/${RELEASE_VERSION}/operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu
          chmod +x operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu
          mkdir -p /usr/local/bin/ 
          mv operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu /usr/local/bin/operator-sdk
          operator-sdk version

      - name: Build Docker Image
        run: operator build wosai/elastic-env-operatpr:v0.0.1

      - name: Log into DockerHub
        run: docker login --username {{.secrets.DOCKERHUB_ORG_USERNAME}} --password {{.secrets.DOCKERHUB_ORG_ACCESS_TOKEN}}

      - name: Push Docker Image
        run: docker push wosai/elastic-env-operatpr:v0.0.1
