name: Release
on:
  release:
    types:
      - created

jobs:
  release:
    name: Release on GitHub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.17"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        timeout-minutes: 20
        with:
          context: .
          push: true
          tags: |
            ghcr.io/shouqianba-ft/elastic-env-operator:${{ github.event.release.tag_name }}
          platforms: linux/amd64
          labels: ${{ steps.meta.outputs.labels }}